
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/topics"
  to = "/topics/webdev/"
  status = 308

[[redirects]]
  from = "/faqs"
  to = "/blog/faqs/"
  status = 301

[[redirects]]
  from = "/github"
  to = "https://github.com/whitep4nth3r"
  status = 301

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/GQbXUVCneJ"
  status = 301